- id: riot-x
  name: Riot X
  subhead: Conquer any challenge with ALPHA ONE Single-Beam Rear Suspension.
  details: Riot X offers unmatched versatility with available ALPHA ONE Single-Beam Rear Suspension and now with ATAC Adjustable-On-The-Fly suspension to handle trails and backcountry riding. 
  image: https://arcticcat.stagesr.com/sites/default/files/_images/vehicle_page/marquee/vehicle/RIOT_X_8000_146_2-6_ES_IFP_US_Red_profile-right_1400x560_sm.png
  starting_price: $13,565
- id: blast-m
  name: Blast M
  subhead:  Mid-Sized Sled Built for the Mountain, with Legendary ALPHA ONE Suspension.
  details: BLAST™ M sets the standard for mid-sized sleds. Armed with the incredible maneuverability of ALPHA ONE™ Single-Beam Rear Suspension, it makes it easier for all types of riders to take on challenging terrain. 
  image: https://arcticcat.stagesr.com/sites/default/files/_images/vehicle_page/marquee/vehicle/BLAST_4000_M_US_Orange_profile-right_1400x560_sm.png
  starting_price: $8,265
- id: blast-lt
  name: BLAST LT
  subhead:  Unrivaled Work-Hard, Play-Hard Versatility in a Mid-Sized Sled
  details: BLAST™ LT is built for working and riding on your terms. With a collection of productivity-focused features, it helps you get things done faster. And when the job is finished, this lighter, more responsive sled offers a fun action-packed experience to any rider. 
  image: https://arcticcat.stagesr.com/sites/default/files/_images/vehicle_page/marquee/vehicle/BLAST_4000_LT_US_Red_profile-right_1400x560_sm.png
  starting_price: $8,265
- id: wildcat-xx
  name: Wildcat XX
  subhead:  Go Anywhere. Ride Over Everything.
  details: Built to handle boldly, corner ruthlessly and dominate the most extreme terrain. 
  image: https://arcticcat.stagesr.com/sites/default/files/_images/vehicle_page/marquee/vehicle/2021-Wildcat%20XX_Red%26amp%3BGrey_1400x1050-min.png
  starting_price: $19,999